const ESC = '\x1b';
const CSI = ESC + '[';

const ansi = {
  clear: CSI + '2J' + CSI + 'H',
  hideCursor: CSI + '?25l',
  showCursor: CSI + '?25h',
  barCursor: CSI + '6 q',
  blockCursor: CSI + '2 q',
  reset: CSI + '0m',
  bold: CSI + '1m',
  dim: CSI + '2m',
  italic: CSI + '3m',
  inverse: CSI + '7m',
  underline: CSI + '4m',
  noBold: CSI + '22m',
  noItalic: CSI + '23m',
  noUnderline: CSI + '24m',
  noInverse: CSI + '27m',
  moveTo: (row, col) => `${CSI}${row};${col}H`,
  fg: {
    default: CSI + '39m',
    dim: CSI + '90m',
    red: CSI + '31m',
    green: CSI + '32m',
    yellow: CSI + '33m',
    blue: CSI + '34m',
    magenta: CSI + '35m',
    cyan: CSI + '36m',
    white: CSI + '37m',
    brightBlack: CSI + '90m',
    brightRed: CSI + '91m',
    brightGreen: CSI + '92m',
    brightYellow: CSI + '93m',
    brightBlue: CSI + '94m',
    brightMagenta: CSI + '95m',
    brightCyan: CSI + '96m',
    brightWhite: CSI + '97m',
  },
  bg: {
    default: CSI + '49m',
    black: CSI + '40m',
    red: CSI + '41m',
    green: CSI + '42m',
    yellow: CSI + '43m',
    blue: CSI + '44m',
    magenta: CSI + '45m',
    cyan: CSI + '46m',
    white: CSI + '47m',
    brightBlack: CSI + '100m',
    brightRed: CSI + '101m',
    brightGreen: CSI + '102m',
    brightYellow: CSI + '103m',
    brightBlue: CSI + '104m',
    brightMagenta: CSI + '105m',
    brightCyan: CSI + '106m',
    brightWhite: CSI + '107m',
    active: CSI + '100m',
    selected: CSI + '44m',
    dirty: CSI + '43m',
  },
};

const colors = {
  title: ansi.fg.brightBlue,
  border: ansi.dim,
  dim: ansi.dim,
  treeDir: ansi.fg.brightCyan,
  treeFile: ansi.fg.default,
  active: ansi.bg.active,
  selected: ansi.bg.selected,
  dirty: ansi.fg.yellow,
  saved: ansi.fg.green,
  error: ansi.fg.red,
  status: ansi.fg.dim,
  lineNo: ansi.fg.dim,
};

module.exports = { ESC, CSI, ansi, colors };
